#!/usr/bin/env node
// A helper script to run the dev scripts
const { spawn } = require('child_process');
const path = require('path');

const bin = b => path.resolve(__dirname, 'node_modules', '.bin', b);

function execute(cmd, extra) {
  switch (cmd) {
    case 'clean':
      return spawn(bin('rimraf'), ['./dist'].concat(extra), {
        stdio: 'inherit',
      });

    case 'lint':
      return spawn(bin('eslint'), ['./src'].concat(extra), {
        stdio: 'inherit',
      });

    case 'build':
      return spawn(bin('babel'), ['./src', '-d', './dist'].concat(extra), {
        stdio: 'inherit',
      });

    case 'test':
      return spawn(bin('jest'), ['--rootDir', '.'].concat(extra), {
        stdio: 'inherit',
      });

    default:
      return spawn(bin(cmd), process.argv.slice(3), {
        stdio: ['inherit', 'inherit', 'inherit'],
      });
  }
}

const proc = execute(process.argv[2], process.argv.slice(3));
proc.on('exit', (code) => {
  process.exit(code);
});
